# Generated by Django 5.2.7 on 2026-06-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('matches', '0001_initial'),
        ('squads', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='squads.squad'),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.venue'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', through='matches.MatchTeam', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='matchteam',
            index=models.Index(fields=['match'], name='MatchTeams_match_i_2676b3_idx'),
        ),
        migrations.AddIndex(
            model_name='matchteam',
            index=models.Index(fields=['team'], name='MatchTeams_team_id_8e60dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchteam',
            unique_together={('match', 'team')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['squad', 'datetime'], name='Matches_squad_i_da8dc6_idx'),
        ),
    ]
