# Generated by Django 5.2.7 on 2026-02-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='squads.squad'),
        ),
    ]
