# Generated by Django 5.2.7 on 2026-06-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squadadmin',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='squads.squad'),
        ),
        migrations.AddField(
            model_name='squadadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_admin_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='admins',
            field=models.ManyToManyField(related_name='created_squads', through='squads.SquadAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_memberships', to='squads.squad'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_member_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(related_name='squads', through='squads.SquadMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='squadadmin',
            index=models.Index(fields=['squad'], name='SquadAdmins_squad_i_b85cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='squadadmin',
            index=models.Index(fields=['user'], name='SquadAdmins_user_id_a1934e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squadadmin',
            unique_together={('squad', 'user')},
        ),
        migrations.AddIndex(
            model_name='squadmember',
            index=models.Index(fields=['squad'], name='SquadMember_squad_i_c0e707_idx'),
        ),
        migrations.AddIndex(
            model_name='squadmember',
            index=models.Index(fields=['user'], name='SquadMember_user_id_bd438e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='squadmember',
            unique_together={('squad', 'user')},
        ),
    ]
